---
- name: Install httpd on RedHat
  hosts: webservers
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present
    - name: Restart httpd service
      service:
        name: httpd
        state: started
        enabled: yes


